name: Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

defaults:
  run:
    working-directory: "./"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_lint_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        shard: [1/2, 2/2]

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node
        uses: ./.github/actions/setup_node

      - name: lint
        if: matrix.shard == '2/2'
        run: pnpm lint

      - name: test
        env:
          TEST_SHARD: ${{ matrix.shard }}
        run: pnpm test
